export const projectlist = [
  {
    id: 1,
    images: [
      { id: 1, img: "/odc_front.jpg" },
      { id: 2, img: "/odc-pipes-2.jpg" },
      { id: 3, img: "/odc-pipes-3.jpg" },
      { id: 4, img: "/odc-ship.jpg" },
      { id: 5, img: "/odc-tbt.jpg" },
    ],
    date: "25th October 2024",
    img: "odc_front.jpg",
    title: "Oman Dry Dock Company",
    desc: "Ship maintenance works for Oman Dry Dock Company",
    featured: true,
  },
  {
    id: 2,
    images: [{ id: 1, img: "mech-sanvira.jpg" }],
    date: "25th October 2024",
    img: "mech-sanvira.jpg",
    title: "Sanvira",
    desc: "Mechanical Works at Sanvira",
    featured: true,
  },
  {
    id: 3,
    images: [{ id: 1, img: "/suh.jpg" }],
    date: "25th October 2024",
    img: "/suh.jpg",
    title: "Suhail Chemicals",
    desc: "Civil, Mechanical and Electrical works for Suhail Chemicals",
    featured: true,
  },
  {
    id: 4,
    images: [
      { id: 1, img: "/pedestrian-bridge-5.jpg" },
      { id: 1, img: "/pedestrian-bridge.jpg" },
      { id: 2, img: "/pedestrian-bridge-2.jpg" },
      { id: 1, img: "/pedestrian-bridge-3.jpg" },
      { id: 1, img: "/pedestrian-bridge-4.jpg" },
    ],
    date: "25th October 2024",
    img: "/pedestrian-bridge-5.jpg",
    title: "Liwa Pedestrian Bridge",
    desc: "Pedestrian Over Bridge in Liwa",
    featured: true,
  },
  {
    id: 5,
    images: [{ id: 1, img: "/water-treatment-2.jpg" }],
    date: "25th October 2024",
    img: "water-treatment-2.jpg",
    title: "Toshiba Water Treatment Plant",
    desc: "Toshiba water treatment plant",
    featured: false,
  },
  {
    id: 6,
    images: [{ id: 1, img: "/jindal2.jpg" }],
    date: "25th October 2024",
    img: "/jindal2.jpg",
    title: "Vulcan Jindal",
    desc: "Vulcan Jindal Mechanical Works",
    featured: false,
  },
  {
    id: 7,
    images: [{ id: 1, img: "/hanoon.jpg" }],
    date: "25th October 2024",
    img: "/hanoon.jpg",
    title: "Hanoon Edible Oil Refinery",
    desc: "Civil, Mechanical and Electrical works for Hanoon Oil Refinery",
    featured: false,
  },
  {
    id: 8,
    images: [
      { id: 1, img: "/fish_interior.jpg" },
      { id: 2, img: "/fish_interior-2.jpg" },
      { id: 3, img: "/fish_front.jpg" },
    ],
    date: "25th October 2024",
    img: "/fish_interior.jpg",
    title: "Qurayat Fish Processing Plant",
    desc: "Fish processing plant and feed store in Qurayat",
    featured: false,
  },

  {
    id: 9,
    images: [{ id: 1, img: "/aas.jpg" }],
    date: "25th October 2024",
    img: "/aas.jpg",
    title: "Aviation Academy Suhar",
    desc: "Landscaping works for Suhar Aviation Academy",
    featured: false,
  },
  {
    id: 10,
    images: [
      { id: 1, img: "/ramez.jpg" },
      { id: 2, img: "/ramez-2.jpg" },
    ],
    date: "25th October 2024",
    img: "/ramez.jpg",
    title: "Ramez International",
    desc: "Civil, Mechanical and MEP works for Ramez International",
    featured: false,
  },

  {
    id: 14,
    images: [{ id: 1, img: "/sohar_flour_mills-1.png" }],
    date: "25th October 2024",
    img: "sohar_flour_mills-1.png",
    title: "Sohar Flour Mills",
    desc: "Civil & Steel Structural Works for Ship Unloader Conveyor",
    featured: false,
  },
  {
    id: 11,
    images: [{ id: 1, img: "/mobile-tower_upscayl.png" }],
    date: "25th October 2024",
    img: "mobile-tower_upscayl.png",
    title: "Mobile Tower Erection",
    desc: "Tower Erection Works",
    featured: false,
  },

  {
    id: 13,
    images: [
      { id: 1, img: "/intelligent-parking.jpg" },
      { id: 2, img: "/intelligent-parking-2.jpg" },
    ],
    date: "25th October 2024",
    img: "intelligent-parking.jpg",
    title: "Intelligent Parking System",
    desc: "Intelligent Parking System in Al Khuwair",
    featured: false,
  },

  {
    id: 12,
    images: [{ id: 1, img: "/sac.jpg" }],
    date: "25th October 2024",
    img: "sac.jpg",
    title: "Sohar Advanced Chemicals",
    desc: "Civil, MEP and Mechanical works for Sohar Advanced Chemicals",
    featured: false,
  },
];
